unit-test:
  image: gradle:alpine
  stage: build
  timeout: 10 minutes
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    # - apk update
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean test --info

cache:
  paths:
    - .gradle/caches
