unit-test:
  image: registry.mitchelltsutsulis.com/mitchellwt/tube_loader_android_build_container:latest
  stage: build
  timeout: 10 minutes
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    # - apk update
    - export ANDROID_HOME=/home/gradle/Android
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean testDebugUnitTest --info

cache:
  paths:
    - .gradle/caches
